// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBobKUzyZtFSYsA_lkr6uD4kSaFznRgj8M',
    appId: '1:771412081414:web:96fa0c70947fdc7fdc7c87',
    messagingSenderId: '771412081414',
    projectId: 'autofirebase-130d4',
    authDomain: 'autofirebase-130d4.firebaseapp.com',
    databaseURL: 'https://autofirebase-130d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'autofirebase-130d4.appspot.com',
    measurementId: 'G-0Z8DR9Z9NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjwIX0YBG0AbkSXmX2RGDxDe7NBcXDknI',
    appId: '1:771412081414:android:b0187fa53b1db23cdc7c87',
    messagingSenderId: '771412081414',
    projectId: 'autofirebase-130d4',
    databaseURL: 'https://autofirebase-130d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'autofirebase-130d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWOnuM0G-hAXywAEqWL_w2k6dMo42JkDo',
    appId: '1:771412081414:ios:5e346a173d1bbd96dc7c87',
    messagingSenderId: '771412081414',
    projectId: 'autofirebase-130d4',
    databaseURL: 'https://autofirebase-130d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'autofirebase-130d4.appspot.com',
    androidClientId: '771412081414-kdhn6u3hlt534e0cij6touoof0srtiok.apps.googleusercontent.com',
    iosClientId: '771412081414-7lncu79n5iqpiivlaoi056nmmna89hm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.weattherStation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWOnuM0G-hAXywAEqWL_w2k6dMo42JkDo',
    appId: '1:771412081414:ios:5e346a173d1bbd96dc7c87',
    messagingSenderId: '771412081414',
    projectId: 'autofirebase-130d4',
    databaseURL: 'https://autofirebase-130d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'autofirebase-130d4.appspot.com',
    androidClientId: '771412081414-kdhn6u3hlt534e0cij6touoof0srtiok.apps.googleusercontent.com',
    iosClientId: '771412081414-7lncu79n5iqpiivlaoi056nmmna89hm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.weattherStation',
  );
}
